name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - name: Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run release
        run: |
          echo "OLD_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          npm run release
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Push changes
        if: env.OLD_VERSION != env.NEW_VERSION
        run: git push origin HEAD:main --follow-tags
      - name: Create GitHub Release
        if: env.OLD_VERSION != env.NEW_VERSION
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
